; ESP32-S3 N16R8 - GB/GBC Emulator

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

; flash & PSRAM (N16R8)
board_build.flash_size = 16MB
board_build.arduino.memory_type = dio_opi
board_build.partitions = default_16MB.csv
board_upload.flash_size = 16MB

; filesystem buat ROM
board_build.filesystem = littlefs

lib_deps =
    bodmer/TFT_eSPI @ ^2.5.43

; pin TFT_eSPI, edit kalau wiring beda
build_flags =
    -DUSER_SETUP_LOADED=1
    -DST7789_DRIVER=1
    -DTFT_WIDTH=135
    -DTFT_HEIGHT=240
    -DTFT_MISO=-1
    -DTFT_MOSI=14
    -DTFT_SCLK=13
    -DTFT_CS=10
    -DTFT_DC=11
    -DTFT_RST=12
    -DTFT_BL=9
    -DTFT_BACKLIGHT_ON=HIGH
    -DLOAD_GLCD=1
    -DLOAD_FONT2=1
    -DSPI_FREQUENCY=40000000
    -DBOARD_HAS_PSRAM
